package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/node/workspace/Corretto8/generic_linux/x64/build/Corretto8Src/installers/linux/universal/tar/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, April 17, 2023 10:45:40 PM UTC
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
     * state is changed.
     */
  public static final short value = (short)(0);
}
