package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/node/workspace/Corretto8/generic_linux/x64/build/Corretto8Src/installers/linux/universal/tar/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, April 17, 2023 10:45:40 PM UTC
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
  	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
  	 */
  public static final int value = (int)(20L);
}
