package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/node/workspace/Corretto8/generic_linux/x64/build/Corretto8Src/installers/linux/universal/tar/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Monday, April 17, 2023 10:45:40 PM UTC
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
     * Constant, defined in the Messaging spec, to define how far the 
     * request shall progress before control is returned to the client.
     */
  public static final short value = (short)(1);
}
