package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/jenkins/node/workspace/Corretto8/generic_linux/x64/build/Corretto8Src/installers/linux/universal/tar/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Monday, April 17, 2023 10:45:40 PM UTC
*/

public interface TransactionService
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CosTSInteroperation.PropogationContext</code> defined in 
       * <i>CORBAservices: Common Object Services Specifications.</i>
       */
  public static final int value = (int)(0L);
}
